### ISSUE TITLE
Infinite yield possible on 'ReplicatedStorage.Resources:WaitForChild("RemoteEvents")'

### ISSUE THREAD

**Issue by iborek** [RoStrap/Resources#34]
Hello. 

I have this issue. Can you help me please?

![screenshot_6](https://user-images.githubusercontent.com/31574803/51078813-be5d6d00-16bb-11e9-8ec9-7029cf3f844c.png)

**Comment by Validark** [comment]
Did you require "Resources" and "Sentry" on the server? It should look like this somewhere on the server:

```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Resources = require(ReplicatedStorage:WaitForChild("Resources"))
local Sentry = Resources:LoadLibrary("Sentry")
```

**Comment by Validark** [comment]
Have you figured it out?

**Comment by iborek** [comment]
Yeah. Thanks for help.

**Comment by Validark** [comment]
I am going to release an update for the Resources library today that will make the warning message more clear.
