### ISSUE TITLE
LoadLibrary is going to be removed so the code won't work anymore after january 6

### ISSUE THREAD

**Issue by darkness4life14** [RoStrap/Resources#37]
On the devforums it says that the loadlibrary will be removed and the rostrap looks to me as it's using loadlibrary (https://devforum.roblox.com/t/loadlibrary-is-going-to-be-removed-on-january-6th/382516)
So you should probably fix that before the update because cmdr uses loadlibrary

**Comment by evaera** [comment]
RoStrap does not use LoadLibrary.

**Comment by Validark** [comment]
To clarify, RoStrap has a function named `LoadLibrary` which is defined [here](https://github.com/RoStrap/Resources/blob/09c3fed21d5463bf9f43d2149c306741406b76c2/Resources.lua#L234-L284). We do not use the built-in function mentioned in that devforum article. If we did, you'd get a warning message (or an error message after Jan 6th)
