### ISSUE TITLE
Nevermore vs NevermoreFramework

### ISSUE THREAD

**Issue by devSparkle** [RoStrap/Resources#4]
I feel it's important to debate our rename of the main framework file from `NevermoreFramework` to `Nevermore`. This is an issue which would affect compatibility with prior versions of Nevermore, as noted in #3.

**Comment by Narrev** [comment]
Prior versions of Nevermore are like 6 years old. I'll continue to open-source and release quality modules for this repository, as Quenty isn't as committed.

We also have different standards regarding what should be in modules. Older versions of Nevermore also included pythonesque functions, sort of antithetical to the batteries not included philosophy. Modules should only include functions that SHOULDN'T be written out each time.

**Comment by Narrev** [comment]
Maybe we should rename the project to Replicator or ResourceManager or something. We should distance the module and organization from Quenty's NevermoreEngine. NevermoreEngine is going to go in its own direction, keeping outdated modules from 5 years ago and with little to no documentation. NevermoreEngine prefers consecutive function calls with decently descriptive method naming to actual documentation, leaving the user to figure out which methods are internal and which are external.

**Comment by Validark** [comment]
Moved to `RoStrap` and `Resources`
